In [2]:
from google.colab import files

uploaded = files.upload()

Saving marketing_campaign.csv to marketing_campaign.csv

In [3]:
import pandas as pd

df = pd.read_csv("marketing_campaign.csv", sep=None, engine="python")

print("Rows and Columns:", df.shape)

Rows and Columns: (2240, 29)

In [4]:
print("Column Names:")
print(df.columns.tolist())

print("\nFirst 5 Rows:")
display(df.head())

print("\nData Types:")
print(df.dtypes)

print("\nMissing Values:")
print(df.isnull().sum())

print("\nDuplicate Rows:")
print(df.duplicated().sum())

Column Names:
['ID', 'Year_Birth', 'Education', 'Marital_Status', 'Income', 'Kidhome', 'Teenhome', 'Dt_Customer', 'Recency', 'MntWines', 'MntFruits', 'MntMeatProducts', 'MntFishProducts', 'MntSweetProducts', 'MntGoldProds', 'NumDealsPurchases', 'NumWebPurchases', 'NumCatalogPurchases', 'NumStorePurchases', 'NumWebVisitsMonth', 'AcceptedCmp3', 'AcceptedCmp4', 'AcceptedCmp5', 'AcceptedCmp1', 'AcceptedCmp2', 'Complain', 'Z_CostContact', 'Z_Revenue', 'Response']

First 5 Rows:

,ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,NumWebVisitsMonth,AcceptedCmp3,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Complain,Z_CostContact,Z_Revenue,Response
0,5524,1957,Graduation,Single,58138.0,0,0,04-09-2012,58,635,...,7,0,0,0,0,0,0,3,11,1
1,2174,1954,Graduation,Single,46344.0,1,1,08-03-2014,38,11,...,5,0,0,0,0,0,0,3,11,0
2,4141,1965,Graduation,Together,71613.0,0,0,21-08-2013,26,426,...,4,0,0,0,0,0,0,3,11,0
3,6182,1984,Graduation,Together,26646.0,1,0,10-02-2014,26,11,...,6,0,0,0,0,0,0,3,11,0
4,5324,1981,PhD,Married,58293.0,1,0,19-01-2014,94,173,...,5,0,0,0,0,0,0,3,11,0

Data Types:
ID                       int64
Year_Birth               int64
Education               object
Marital_Status          object
Income                 float64
Kidhome                  int64
Teenhome                 int64
Dt_Customer             object
Recency                  int64
MntWines                 int64
MntFruits                int64
MntMeatProducts          int64
MntFishProducts          int64
MntSweetProducts         int64
MntGoldProds             int64
NumDealsPurchases        int64
NumWebPurchases          int64
NumCatalogPurchases      int64
NumStorePurchases        int64
NumWebVisitsMonth        int64
AcceptedCmp3             int64
AcceptedCmp4             int64
AcceptedCmp5             int64
AcceptedCmp1             int64
AcceptedCmp2             int64
Complain                 int64
Z_CostContact            int64
Z_Revenue                int64
Response                 int64
dtype: object

Missing Values:
ID                      0
Year_Birth              0
Education               0
Marital_Status          0
Income                 24
Kidhome                 0
Teenhome                0
Dt_Customer             0
Recency                 0
MntWines                0
MntFruits               0
MntMeatProducts         0
MntFishProducts         0
MntSweetProducts        0
MntGoldProds            0
NumDealsPurchases       0
NumWebPurchases         0
NumCatalogPurchases     0
NumStorePurchases       0
NumWebVisitsMonth       0
AcceptedCmp3            0
AcceptedCmp4            0
AcceptedCmp5            0
AcceptedCmp1            0
AcceptedCmp2            0
Complain                0
Z_CostContact           0
Z_Revenue               0
Response                0
dtype: int64

Duplicate Rows:
0

In [5]:
# Show rows where Income is missing
missing_income = df[df["Income"].isnull()]

print("Number of missing Income values:", missing_income.shape[0])

display(missing_income)

Number of missing Income values: 24

,ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,NumWebVisitsMonth,AcceptedCmp3,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Complain,Z_CostContact,Z_Revenue,Response
10,1994,1983,Graduation,Married,NaN,1,0,15-11-2013,11,5,...,7,0,0,0,0,0,0,3,11,0
27,5255,1986,Graduation,Single,NaN,1,0,20-02-2013,19,5,...,1,0,0,0,0,0,0,3,11,0
43,7281,1959,PhD,Single,NaN,0,0,05-11-2013,80,81,...,2,0,0,0,0,0,0,3,11,0
48,7244,1951,Graduation,Single,NaN,2,1,01-01-2014,96,48,...,6,0,0,0,0,0,0,3,11,0
58,8557,1982,Graduation,Single,NaN,1,0,17-06-2013,57,11,...,6,0,0,0,0,0,0,3,11,0
71,10629,1973,2n Cycle,Married,NaN,1,0,14-09-2012,25,25,...,8,0,0,0,0,0,0,3,11,0
90,8996,1957,PhD,Married,NaN,2,1,19-11-2012,4,230,...,9,0,0,0,0,0,0,3,11,0
91,9235,1957,Graduation,Single,NaN,1,1,27-05-2014,45,7,...,7,0,0,0,0,0,0,3,11,0
92,5798,1973,Master,Together,NaN,0,0,23-11-2013,87,445,...,1,0,0,0,0,0,0,3,11,0
128,8268,1961,PhD,Married,NaN,0,1,11-07-2013,23,352,...,6,0,0,0,0,0,0,3,11,0
133,1295,1963,Graduation,Married,NaN,0,1,11-08-2013,96,231,...,4,0,0,0,0,0,0,3,11,0
312,2437,1989,Graduation,Married,NaN,0,0,03-06-2013,69,861,...,3,0,1,0,1,0,0,3,11,0
319,2863,1970,Graduation,Single,NaN,1,2,23-08-2013,67,738,...,7,0,1,0,1,0,0,3,11,0
1379,10475,1970,Master,Together,NaN,0,1,01-04-2013,39,187,...,5,0,0,0,0,0,0,3,11,0
1382,2902,1958,Graduation,Together,NaN,1,1,03-09-2012,87,19,...,5,0,0,0,0,0,0,3,11,0
1383,4345,1964,2n Cycle,Single,NaN,1,1,12-01-2014,49,5,...,7,0,0,0,0,0,0,3,11,0
1386,3769,1972,PhD,Together,NaN,1,0,02-03-2014,17,25,...,7,0,0,0,0,0,0,3,11,0
2059,7187,1969,Master,Together,NaN,1,1,18-05-2013,52,375,...,3,0,0,0,0,0,0,3,11,0
2061,1612,1981,PhD,Single,NaN,1,0,31-05-2013,82,23,...,6,0,0,0,0,0,0,3,11,0
2078,5079,1971,Graduation,Married,NaN,1,1,03-03-2013,82,71,...,8,0,0,0,0,0,0,3,11,0
2079,10339,1954,Master,Together,NaN,0,1,23-06-2013,83,161,...,6,0,0,0,0,0,0,3,11,0
2081,3117,1955,Graduation,Single,NaN,0,1,18-10-2013,95,264,...,7,0,0,0,0,0,0,3,11,0
2084,5250,1943,Master,Widow,NaN,0,0,30-10-2013,75,532,...,1,0,0,1,0,0,0,3,11,1
2228,8720,1978,2n Cycle,Together,NaN,0,0,12-08-2012,53,32,...,0,0,1,0,0,0,0,3,11,0

In [6]:
print("Income Statistics:")
print(df["Income"].describe())

Income Statistics:
count      2216.000000
mean      52247.251354
std       25173.076661
min        1730.000000
25%       35303.000000
50%       51381.500000
75%       68522.000000
max      666666.000000
Name: Income, dtype: float64

In [7]:
print("Income Median:", df["Income"].median())
print("Income Mean:", df["Income"].mean())

Income Median: 51381.5
Income Mean: 52247.25135379061

In [8]:
# Fill missing Income values with the median
income_median = df["Income"].median()

df["Income"] = df["Income"].fillna(income_median)

print("Missing Income values after cleaning:")
print(df["Income"].isnull().sum())

Missing Income values after cleaning:
0

In [9]:
print("Missing values in each column:")
print(df.isnull().sum())

Missing values in each column:
ID                     0
Year_Birth             0
Education              0
Marital_Status         0
Income                 0
Kidhome                0
Teenhome               0
Dt_Customer            0
Recency                0
MntWines               0
MntFruits              0
MntMeatProducts        0
MntFishProducts        0
MntSweetProducts       0
MntGoldProds           0
NumDealsPurchases      0
NumWebPurchases        0
NumCatalogPurchases    0
NumStorePurchases      0
NumWebVisitsMonth      0
AcceptedCmp3           0
AcceptedCmp4           0
AcceptedCmp5           0
AcceptedCmp1           0
AcceptedCmp2           0
Complain               0
Z_CostContact          0
Z_Revenue              0
Response               0
dtype: int64

In [10]:
print("Duplicate rows before cleaning:", df.duplicated().sum())

Duplicate rows before cleaning: 0

In [11]:
df = df.drop_duplicates()

print("Duplicate rows after cleaning:", df.duplicated().sum())

Duplicate rows after cleaning: 0

In [12]:
print("Final dataset shape:", df.shape)

Final dataset shape: (2240, 29)

In [13]:
print("Education values:")
print(df["Education"].value_counts())

Education values:
Education
Graduation    1127
PhD            486
Master         370
2n Cycle       203
Basic           54
Name: count, dtype: int64

In [14]:
print("\nMarital Status values:")
print(df["Marital_Status"].value_counts())

Marital Status values:
Marital_Status
Married     864
Together    580
Single      480
Divorced    232
Widow        77
Alone         3
Absurd        2
YOLO          2
Name: count, dtype: int64

In [15]:
text_columns = df.select_dtypes(include="object").columns

print("Text columns:")
print(text_columns.tolist())

for col in text_columns:
    print(f"\n--- {col} ---")
    print(df[col].value_counts().head(20))

Text columns:
['Education', 'Marital_Status', 'Dt_Customer']

--- Education ---
Education
Graduation    1127
PhD            486
Master         370
2n Cycle       203
Basic           54
Name: count, dtype: int64

--- Marital_Status ---
Marital_Status
Married     864
Together    580
Single      480
Divorced    232
Widow        77
Alone         3
Absurd        2
YOLO          2
Name: count, dtype: int64

--- Dt_Customer ---
Dt_Customer
31-08-2012    12
12-05-2014    11
14-02-2013    11
12-09-2012    11
22-05-2014    10
20-08-2013    10
02-01-2013     9
23-03-2014     9
05-04-2014     9
29-10-2012     9
01-03-2014     9
11-05-2014     8
07-11-2013     8
29-08-2012     8
05-04-2013     8
22-08-2012     8
03-06-2013     8
17-08-2012     8
23-11-2012     8
28-10-2013     8
Name: count, dtype: int64

In [16]:
# Remove leading/trailing spaces from text columns
text_columns = df.select_dtypes(include="object").columns

for col in text_columns:
    df[col] = df[col].str.strip()

print("Extra spaces removed from text columns.")

Extra spaces removed from text columns.

In [17]:
df["Education"] = df["Education"].replace({
    "2n Cycle": "2nd Cycle"
})

print(df["Education"].value_counts())

Education
Graduation    1127
PhD            486
Master         370
2nd Cycle      203
Basic           54
Name: count, dtype: int64

In [18]:
df["Marital_Status"] = df["Marital_Status"].str.title()

print(df["Marital_Status"].value_counts())

Marital_Status
Married     864
Together    580
Single      480
Divorced    232
Widow        77
Alone         3
Absurd        2
Yolo          2
Name: count, dtype: int64

In [19]:
print("Education values:")
print(df["Education"].unique())

print("\nMarital Status values:")
print(df["Marital_Status"].unique())

Education values:
['Graduation' 'PhD' 'Master' 'Basic' '2nd Cycle']

Marital Status values:
['Single' 'Together' 'Married' 'Divorced' 'Widow' 'Alone' 'Absurd' 'Yolo']

In [20]:
df["Dt_Customer"] = pd.to_datetime(
    df["Dt_Customer"],
    format="%d-%m-%Y",
    errors="coerce"
)

print(df["Dt_Customer"].head())

0   2012-09-04
1   2014-03-08
2   2013-08-21
3   2014-02-10
4   2014-01-19
Name: Dt_Customer, dtype: datetime64[ns]

In [21]:
print("Dt_Customer data type:")
print(df["Dt_Customer"].dtype)

Dt_Customer data type:
datetime64[ns]

In [22]:
print("Missing/invalid dates:")
print(df["Dt_Customer"].isnull().sum())

Missing/invalid dates:
0

In [23]:
print(
    df["Dt_Customer"]
    .dt.strftime("%d-%m-%Y")
    .head(10)
)

0    04-09-2012
1    08-03-2014
2    21-08-2013
3    10-02-2014
4    19-01-2014
5    09-09-2013
6    13-11-2012
7    08-05-2013
8    06-06-2013
9    13-03-2014
Name: Dt_Customer, dtype: object

In [24]:
df.columns = (
    df.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
)

In [25]:
print(df.columns.tolist())

['id', 'year_birth', 'education', 'marital_status', 'income', 'kidhome', 'teenhome', 'dt_customer', 'recency', 'mntwines', 'mntfruits', 'mntmeatproducts', 'mntfishproducts', 'mntsweetproducts', 'mntgoldprods', 'numdealspurchases', 'numwebpurchases', 'numcatalogpurchases', 'numstorepurchases', 'numwebvisitsmonth', 'acceptedcmp3', 'acceptedcmp4', 'acceptedcmp5', 'acceptedcmp1', 'acceptedcmp2', 'complain', 'z_costcontact', 'z_revenue', 'response']

In [26]:
df.duplicated().sum()

np.int64(0)

In [27]:
df[df.duplicated()]

Empty DataFrame
Columns: [id, year_birth, education, marital_status, income, kidhome, teenhome, dt_customer, recency, mntwines, mntfruits, mntmeatproducts, mntfishproducts, mntsweetproducts, mntgoldprods, numdealspurchases, numwebpurchases, numcatalogpurchases, numstorepurchases, numwebvisitsmonth, acceptedcmp3, acceptedcmp4, acceptedcmp5, acceptedcmp1, acceptedcmp2, complain, z_costcontact, z_revenue, response]
Index: []

[0 rows x 29 columns]

In [28]:
df = df.drop_duplicates()

In [29]:
df.duplicated().sum()

np.int64(0)

In [30]:
df['id'].duplicated().sum()

np.int64(0)

In [31]:
print("Duplicate rows:", df.duplicated().sum())
print("Duplicate IDs:", df['id'].duplicated().sum())
print("Rows:", df.shape[0])

Duplicate rows: 0
Duplicate IDs: 0
Rows: 2240

In [32]:
df.isnull().sum()

id                     0
year_birth             0
education              0
marital_status         0
income                 0
kidhome                0
teenhome               0
dt_customer            0
recency                0
mntwines               0
mntfruits              0
mntmeatproducts        0
mntfishproducts        0
mntsweetproducts       0
mntgoldprods           0
numdealspurchases      0
numwebpurchases        0
numcatalogpurchases    0
numstorepurchases      0
numwebvisitsmonth      0
acceptedcmp3           0
acceptedcmp4           0
acceptedcmp5           0
acceptedcmp1           0
acceptedcmp2           0
complain               0
z_costcontact          0
z_revenue              0
response               0
dtype: int64

In [33]:
missing_percentage = (df.isnull().sum() / len(df)) * 100
print(missing_percentage)

id                     0.0
year_birth             0.0
education              0.0
marital_status         0.0
income                 0.0
kidhome                0.0
teenhome               0.0
dt_customer            0.0
recency                0.0
mntwines               0.0
mntfruits              0.0
mntmeatproducts        0.0
mntfishproducts        0.0
mntsweetproducts       0.0
mntgoldprods           0.0
numdealspurchases      0.0
numwebpurchases        0.0
numcatalogpurchases    0.0
numstorepurchases      0.0
numwebvisitsmonth      0.0
acceptedcmp3           0.0
acceptedcmp4           0.0
acceptedcmp5           0.0
acceptedcmp1           0.0
acceptedcmp2           0.0
complain               0.0
z_costcontact          0.0
z_revenue              0.0
response               0.0
dtype: float64

In [34]:
missing = df.isnull().sum()
missing[missing > 0]

Series([], dtype: int64)

In [35]:
df['income'] = df['income'].fillna(df['income'].median())

In [36]:
df.isnull().sum()

id                     0
year_birth             0
education              0
marital_status         0
income                 0
kidhome                0
teenhome               0
dt_customer            0
recency                0
mntwines               0
mntfruits              0
mntmeatproducts        0
mntfishproducts        0
mntsweetproducts       0
mntgoldprods           0
numdealspurchases      0
numwebpurchases        0
numcatalogpurchases    0
numstorepurchases      0
numwebvisitsmonth      0
acceptedcmp3           0
acceptedcmp4           0
acceptedcmp5           0
acceptedcmp1           0
acceptedcmp2           0
complain               0
z_costcontact          0
z_revenue              0
response               0
dtype: int64

In [37]:
print("Total missing values:", df.isnull().sum().sum())

Total missing values: 0

In [38]:
df['year_birth'].describe()

count    2240.000000
mean     1968.805804
std        11.984069
min      1893.000000
25%      1959.000000
50%      1970.000000
75%      1977.000000
max      1996.000000
Name: year_birth, dtype: float64

In [39]:
df[df['year_birth'] < 1900]

,id,year_birth,education,marital_status,income,kidhome,teenhome,dt_customer,recency,mntwines,...,numwebvisitsmonth,acceptedcmp3,acceptedcmp4,acceptedcmp5,acceptedcmp1,acceptedcmp2,complain,z_costcontact,z_revenue,response
239,11004,1893,2nd Cycle,Single,60182.0,0,1,2014-05-17,23,8,...,4,0,0,0,0,0,0,3,11,0
339,1150,1899,PhD,Together,83532.0,0,0,2013-09-26,36,755,...,1,0,0,1,0,0,0,3,11,0

In [40]:
df['income'].describe()

count      2240.000000
mean      52237.975446
std       25037.955891
min        1730.000000
25%       35538.750000
50%       51381.500000
75%       68289.750000
max      666666.000000
Name: income, dtype: float64

In [41]:
df[df['income'] < 0]

Empty DataFrame
Columns: [id, year_birth, education, marital_status, income, kidhome, teenhome, dt_customer, recency, mntwines, mntfruits, mntmeatproducts, mntfishproducts, mntsweetproducts, mntgoldprods, numdealspurchases, numwebpurchases, numcatalogpurchases, numstorepurchases, numwebvisitsmonth, acceptedcmp3, acceptedcmp4, acceptedcmp5, acceptedcmp1, acceptedcmp2, complain, z_costcontact, z_revenue, response]
Index: []

[0 rows x 29 columns]

In [42]:
df['education'].value_counts()

education
Graduation    1127
PhD            486
Master         370
2nd Cycle      203
Basic           54
Name: count, dtype: int64

In [43]:
df['marital_status'].value_counts()

marital_status
Married     864
Together    580
Single      480
Divorced    232
Widow        77
Alone         3
Absurd        2
Yolo          2
Name: count, dtype: int64

In [46]:
numeric_columns = [
    'mntwines',
    'mntfruits',
    'mntmeatproducts',
    'mntfishproducts',
    'mntsweetproducts',
    'mntgoldprods'
]

for col in numeric_columns:
    print(col, (df[col] < 0).sum())

mntwines 0
mntfruits 0
mntmeatproducts 0
mntfishproducts 0
mntsweetproducts 0
mntgoldprods 0

In [47]:
print(df.columns.tolist())

['id', 'year_birth', 'education', 'marital_status', 'income', 'kidhome', 'teenhome', 'dt_customer', 'recency', 'mntwines', 'mntfruits', 'mntmeatproducts', 'mntfishproducts', 'mntsweetproducts', 'mntgoldprods', 'numdealspurchases', 'numwebpurchases', 'numcatalogpurchases', 'numstorepurchases', 'numwebvisitsmonth', 'acceptedcmp3', 'acceptedcmp4', 'acceptedcmp5', 'acceptedcmp1', 'acceptedcmp2', 'complain', 'z_costcontact', 'z_revenue', 'response']

In [48]:
df['recency'].describe()

count    2240.000000
mean       49.109375
std        28.962453
min         0.000000
25%        24.000000
50%        49.000000
75%        74.000000
max        99.000000
Name: recency, dtype: float64

In [49]:
df[df['recency'] < 0]

Empty DataFrame
Columns: [id, year_birth, education, marital_status, income, kidhome, teenhome, dt_customer, recency, mntwines, mntfruits, mntmeatproducts, mntfishproducts, mntsweetproducts, mntgoldprods, numdealspurchases, numwebpurchases, numcatalogpurchases, numstorepurchases, numwebvisitsmonth, acceptedcmp3, acceptedcmp4, acceptedcmp5, acceptedcmp1, acceptedcmp2, complain, z_costcontact, z_revenue, response]
Index: []

[0 rows x 29 columns]

In [50]:
for col in df.select_dtypes(include='object').columns:
    print("\n", col)
    print(df[col].unique())

 education
['Graduation' 'PhD' 'Master' 'Basic' '2nd Cycle']

 marital_status
['Single' 'Together' 'Married' 'Divorced' 'Widow' 'Alone' 'Absurd' 'Yolo']

In [ ]:
print(df.dtypes)

In [51]:
print(df.dtypes)

id                              int64
year_birth                      int64
education                      object
marital_status                 object
income                        float64
kidhome                         int64
teenhome                        int64
dt_customer            datetime64[ns]
recency                         int64
mntwines                        int64
mntfruits                       int64
mntmeatproducts                 int64
mntfishproducts                 int64
mntsweetproducts                int64
mntgoldprods                    int64
numdealspurchases               int64
numwebpurchases                 int64
numcatalogpurchases             int64
numstorepurchases               int64
numwebvisitsmonth               int64
acceptedcmp3                    int64
acceptedcmp4                    int64
acceptedcmp5                    int64
acceptedcmp1                    int64
acceptedcmp2                    int64
complain                        int64
z_costcontact                   int64
z_revenue                       int64
response                        int64
dtype: object

In [54]:
df['dt_customer'] = pd.to_datetime(df['dt_customer'], dayfirst=True)

In [55]:
import pandas as pd

In [56]:
print(df['dt_customer'].dtype)

datetime64[ns]

In [58]:
numeric_columns = [
    'year_birth',
    'income',
    'kidhome',
    'teenhome',
    'recency',
    'mntwines',
    'mntfruits',
    'mntmeatproducts',
    'mntfishproducts',
    'mntsweetproducts',
    'mntgoldprods'
]

print(df[numeric_columns].dtypes)

year_birth            int64
income              float64
kidhome               int64
teenhome              int64
recency               int64
mntwines              int64
mntfruits             int64
mntmeatproducts       int64
mntfishproducts       int64
mntsweetproducts      int64
mntgoldprods          int64
dtype: object

In [59]:
for col in numeric_columns:
    df[col] = pd.to_numeric(df[col], errors='coerce')

In [60]:
print(df.dtypes)

id                              int64
year_birth                      int64
education                      object
marital_status                 object
income                        float64
kidhome                         int64
teenhome                        int64
dt_customer            datetime64[ns]
recency                         int64
mntwines                        int64
mntfruits                       int64
mntmeatproducts                 int64
mntfishproducts                 int64
mntsweetproducts                int64
mntgoldprods                    int64
numdealspurchases               int64
numwebpurchases                 int64
numcatalogpurchases             int64
numstorepurchases               int64
numwebvisitsmonth               int64
acceptedcmp3                    int64
acceptedcmp4                    int64
acceptedcmp5                    int64
acceptedcmp1                    int64
acceptedcmp2                    int64
complain                        int64
z_costcontact                   int64
z_revenue                       int64
response                        int64
dtype: object

In [61]:
df['customer_year'] = df['dt_customer'].dt.year

In [62]:
df[['dt_customer', 'customer_year']].head()

  dt_customer  customer_year
0  2012-09-04           2012
1  2014-03-08           2014
2  2013-08-21           2013
3  2014-02-10           2014
4  2014-01-19           2014

In [64]:
df['customer_month'] = df['dt_customer'].dt.month

In [65]:
df[['dt_customer', 'customer_month']].head()

  dt_customer  customer_month
0  2012-09-04               9
1  2014-03-08               3
2  2013-08-21               8
3  2014-02-10               2
4  2014-01-19               1

In [66]:
df['customer_month_name'] = df['dt_customer'].dt.month_name()

In [67]:
reference_date = df['dt_customer'].max()

df['customer_tenure_years'] = (
    (reference_date - df['dt_customer']).dt.days / 365.25
).round(2)

In [68]:
df[['dt_customer', 'customer_tenure_years']].head()

  dt_customer  customer_tenure_years
0  2012-09-04                   1.82
1  2014-03-08                   0.31
2  2013-08-21                   0.85
3  2014-02-10                   0.38
4  2014-01-19                   0.44

In [69]:
print(df[['dt_customer',
          'customer_year',
          'customer_month',
          'customer_month_name',
          'customer_tenure_years']].head(10))

  dt_customer  customer_year  customer_month customer_month_name  \
0  2012-09-04           2012               9           September
1  2014-03-08           2014               3               March
2  2013-08-21           2013               8              August
3  2014-02-10           2014               2            February
4  2014-01-19           2014               1             January
5  2013-09-09           2013               9           September
6  2012-11-13           2012              11            November
7  2013-05-08           2013               5                 May
8  2013-06-06           2013               6                June
9  2014-03-13           2014               3               March

   customer_tenure_years
0                   1.82
1                   0.31
2                   0.85
3                   0.38
4                   0.44
5                   0.80
6                   1.62
7                   1.14
8                   1.06
9                   0.30

In [70]:
print(df[['customer_year',
          'customer_month',
          'customer_tenure_years']].isnull().sum())

customer_year            0
customer_month           0
customer_tenure_years    0
dtype: int64

In [71]:
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Rows: 2240
Columns: 33

In [72]:
print("Total missing values:", df.isnull().sum().sum())

Total missing values: 0

In [73]:
print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 0

In [74]:
print("Duplicate IDs:", df['id'].duplicated().sum())

Duplicate IDs: 0

In [75]:
print(df.dtypes)

id                                int64
year_birth                        int64
education                        object
marital_status                   object
income                          float64
kidhome                           int64
teenhome                          int64
dt_customer              datetime64[ns]
recency                           int64
mntwines                          int64
mntfruits                         int64
mntmeatproducts                   int64
mntfishproducts                   int64
mntsweetproducts                  int64
mntgoldprods                      int64
numdealspurchases                 int64
numwebpurchases                   int64
numcatalogpurchases               int64
numstorepurchases                 int64
numwebvisitsmonth                 int64
acceptedcmp3                      int64
acceptedcmp4                      int64
acceptedcmp5                      int64
acceptedcmp1                      int64
acceptedcmp2                      int64
complain                          int64
z_costcontact                     int64
z_revenue                         int64
response                          int64
customer_year                     int32
customer_month                    int32
customer_month_name              object
customer_tenure_years           float64
dtype: object

In [77]:
spending_columns = [
    'mntwines',
    'mntfruits',
    'mntmeatproducts',
    'mntfishproducts',
    'mntsweetproducts',
    'mntgoldprods'
]

for col in spending_columns:
    print(col, (df[col] < 0).sum())

mntwines 0
mntfruits 0
mntmeatproducts 0
mntfishproducts 0
mntsweetproducts 0
mntgoldprods 0

In [78]:
print(df[['customer_year',
          'customer_month',
          'customer_month_name',
          'customer_tenure_years']].head())

   customer_year  customer_month customer_month_name  customer_tenure_years
0           2012               9           September                   1.82
1           2014               3               March                   0.31
2           2013               8              August                   0.85
3           2014               2            February                   0.38
4           2014               1             January                   0.44

In [79]:
print("===== FINAL DATA QUALITY CHECK =====")
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])
print("Missing values:", df.isnull().sum().sum())
print("Duplicate rows:", df.duplicated().sum())
print("Duplicate IDs:", df['id'].duplicated().sum())
print("====================================")

===== FINAL DATA QUALITY CHECK =====
Rows: 2240
Columns: 33
Missing values: 0
Duplicate rows: 0
Duplicate IDs: 0
====================================

In [80]:
df.to_csv('marketing_campaign_cleaned.csv', index=False)

In [82]:
import os

print(os.path.exists('marketing_campaign_cleaned.csv'))

True

In [83]:
df_cleaned = pd.read_csv('marketing_campaign_cleaned.csv')

print(df_cleaned.shape)
print(df_cleaned.head())

(2240, 33)
     id  year_birth   education marital_status   income  kidhome  teenhome  \
0  5524        1957  Graduation         Single  58138.0        0         0
1  2174        1954  Graduation         Single  46344.0        1         1
2  4141        1965  Graduation       Together  71613.0        0         0
3  6182        1984  Graduation       Together  26646.0        1         0
4  5324        1981         PhD        Married  58293.0        1         0

  dt_customer  recency  mntwines  ...  acceptedcmp1  acceptedcmp2  complain  \
0  2012-09-04       58       635  ...             0             0         0
1  2014-03-08       38        11  ...             0             0         0
2  2013-08-21       26       426  ...             0             0         0
3  2014-02-10       26        11  ...             0             0         0
4  2014-01-19       94       173  ...             0             0         0

   z_costcontact  z_revenue  response  customer_year  customer_month  \
0              3         11         1           2012               9
1              3         11         0           2014               3
2              3         11         0           2013               8
3              3         11         0           2014               2
4              3         11         0           2014               1

   customer_month_name  customer_tenure_years
0            September                   1.82
1                March                   0.31
2               August                   0.85
3             February                   0.38
4              January                   0.44

[5 rows x 33 columns]

In [84]:
print("Rows:", df_cleaned.shape[0])
print("Columns:", df_cleaned.shape[1])
print("Missing values:", df_cleaned.isnull().sum().sum())
print("Duplicate rows:", df_cleaned.duplicated().sum())

Rows: 2240
Columns: 33
Missing values: 0
Duplicate rows: 0

In [85]:
from google.colab import files

files.download('marketing_campaign_cleaned.csv')

In [86]:
import os
print(os.getcwd())

/content